### ISSUE TITLE
ignore punctuation in element names and attribute values

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/llt-segmenter#11] opened 2014-02-04 19:49 UTC
the segmenter should ignore punctuation in element names and attribute values.

**Comment by LFDM** [comment] 2014-02-04 21:21
Not a bug one should be proud of :) Will fix tomorrow morning.

**Comment by LFDM** [comment] 2014-02-05 11:49
Just to be safe, I am going to add one more spec to 'llt' before I close this.

**Comment by LFDM** [comment] 2014-02-05 12:35
Ok, should be good, cf. latin-language-toolkit/llt@e3234ce

**Closed as completed by LFDM** 2014-02-05 12:35 UTC
